### ISSUE TITLE
What is fmap and gmap?

### ISSUE THREAD

**Issue by JesseZZZZZ** [uzh-rpg/rampvo#1]
Hi, dear authors, thank you for ramp vo, I learnt a lot from your work and planning to conduct a similar work based on DPVO too. My question is, in "ramp/net.py" does "fmap" and "gmap" in the code represent "matching feature" and "context feature" in the paper? Thank you!!!

**Comment by senecobis** [comment]
Hi Jesse, exactly as you said, fmap and gmap are matching feature (used for building the feature pyramid in the matcher) and context feature.

**Comment by JesseZZZZZ** [comment]
@senecobis Thanks✌
