### ISSUE TITLE
ModuleNotFoundError: No module named 'data'

### ISSUE THREAD

**Issue by wynelio** [uzh-rpg/rampvo#2]
Hello, thank u for your excellent work rampvo. When I run this code, I found that some files were missing.
For example, 1. "from data import Events" in rampvo/utils/transformers.py; 2. "from data import H5EventHandle" in rampvo/evaluate.py.
Could you please provide these files? Thank you a lot!
` from data import Events
ModuleNotFoundError: No module named 'data'`

**Comment by senecobis** [comment]
Hi Wynelio, sorry for late reply.
Data folder was added, with all the helper functions to manage events.
Hope you find it useful.

**Comment by wynelio** [comment]
> Hi Wynelio, sorry for late reply. Data folder was added, with all the helper functions to manage events. Hope you find it useful.

Thanks a lot! That's helpful for me!
