### ISSUE TITLE
Problem about the Tartanair Event dataset 

### ISSUE THREAD

**Issue by JesseZZZZZ** [uzh-rpg/rampvo#3]
![image](https://github.com/user-attachments/assets/46024479-3bee-4025-9a4c-5c1584032627)
Hi, dear authors. Can you open this website...? I can't download the dataset throuth the .sh script, nor can I open the link in my browser.....Thank you!

**Comment by senecobis** [comment]
Hi @JesseZZZZZ unfortunately we are experiencing a momentary problem with our servers.
In a couple of days should be solved, thanks for asking.

**Comment by JesseZZZZZ** [comment]
@senecobis I shall wait for it then~ Thanks for your answer.

**Comment by senecobis** [comment]
@JesseZZZZZ the servers are now working, you can download all the data, enjoy ✌🏼

**Comment by JesseZZZZZ** [comment]
Thanks！I've already begin downloading. Thanks for your concern!



---- Replied Message ----
| From | Roberto ***@***.***> |
| Date | 11/07/2024 16:41 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [uzh-rpg/rampvo] Problem about the Tartanair Event dataset (Issue #3) |

@JesseZZZZZ the servers are now working, you can download all the data, enjoy ✌🏼
